development:
  adapter: sqlserver
  mode: odbc
  dsn: mblog
  database: mblog_development
  host: .

test:
  adapter: sqlserver
  mode: odbc
  dsn: mblog
  database: mblog_test
  host: .

acceptance:
  adapter: sqlserver
  mode: odbc
  dsn: mblog
  database: mblog_acceptancetest
  host: .

staging:
  adapter: sqlserver
  mode: odbc
  dsn: mblog
  database: mblog_staging
  host: .

production:
  adapter: sqlserver
  mode: odbc
  dsn: mblog
  database: mblog
  host: .
