//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;

namespace MBlogModel
{
    public class User
    {
        public virtual int Id { get; private set; }
        [Required]
        public virtual string Email { get; private set; }
        [Required]
        public virtual string Name { get; set; }
        public virtual string HashedPassword { get; private set; }
        public virtual string Salt { get; private set; }
        public virtual bool IsAdmin { get; private set; }

        public void AddUser(string name, string email, string password, bool isAdmin)
        {
            Name = name;
            Email = email;
            HashedPassword = password;
            IsAdmin = isAdmin;
            Salt = "this is salt";
        }
    }
}
